config/routes.rb
PostitTemplate::Application.routes.draw do
  
  resources :widgets
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/show', to: 'posts#show'
  get '/show/:id', to: 'posts#index'

  resources 'posts', except: :destroy do
    member do
      post 'vote'
    end
  	resources 'comments', only: [:create, :vote] do
      member do
        post 'vote'
      end
    end
  end

  resources 'categories', only: [:new, :create, :show, :destroy]
  resources 'users', only: [:show, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	include Voteable 

	belongs_to :user
	belongs_to :post

	validates :body, presence: true

		
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

	before_action :require_user
	before_action :set_posts, only: [:create, :vote]


	def create
		@comment = @post.comments.build(params.require(:comment).permit(:body))
		@comment.user = current_user

		if @comment.save
			flash[:notice] = "Your Comment is saved"
			redirect_to post_path(@post)
		else
			render 'posts/show'
		end

	end

	def vote
		#binding pry
		@comment = Comment.find(params[:id])
		@vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])

		respond_to do |format|
			format.html {
				if @vote.valid?
		    		flash[:notice] = 'Your vote was counted'
		    	else
		    		flash[:error] = 'You can vote only once'
		    	end
		    	redirect_to :back

			}
			format.js
		end
		
	end

	def set_posts
		@post = Post.find(params[:post_id])
	end

	
end

app/views/comments/_comment.html.erb
<div class="row">
	<div class="well span0 text-center">
		<% if logged_in? %>
			<%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
					<i class="icon-arrow-up"></i>
			<% end %>
			<br/>
			<% end %>
			<span id="comment_<%= comment.id %>_vote"><%= comment.total_votes %></span> votes
			<br/>
			<% if logged_in? %>
			<%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		<% end %>
	</div>
	<div class="well span8">
		<em><%= comment.body %></em>
		<% if show_post %>
			on <%= link_to comment.post.title, post_path(comment.post) %>
		<% end %>
		<br>
		<span class="quiet">by </span><%= comment.user ? comment.user.username : 'Empty Username' %> 
		<small>at <%= format_date(comment.created_at) %></small>
	</div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
	$("#comment_<%= @comment.id %>_vote").html("<%= @comment.total_votes %>");
<% else %>
	alert("You are allowed to vote only once");
<% end %>