config/routes.rb
PostitTemplate::Application.routes.draw do
  
  resources :widgets
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/show', to: 'posts#show'
  get '/show/:id', to: 'posts#index'

  resources 'posts', except: :destroy do
    member do
      post 'vote'
    end
  	resources 'comments', only: [:create, :vote] do
      member do
        post 'vote'
      end
    end
  end

  resources 'categories', only: [:new, :create, :show, :destroy]
  resources 'users', only: [:show, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base

	include Voteable 
	include Sluggable

	PER_PAGE = 3

	default_scope {order('created_at ASC')}
	
	belongs_to :user
	#belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
	has_many :comments
	has_many :post_categories
	has_many :categories, :through => :post_categories
	
	validates :title, presence: true, length: {minimum: 5}
	validates :url, presence: true
	validates :description, presence: true

	sluggable_column :title	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #include ActionController::Helpers
  #helper CommonHelper

  before_action :set_posts, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]
	
  def index
    @posts = Post.limit(Post::PER_PAGE).offset(params[:offset])
  	#@posts = Post.all.sort_by{|x| x.total_votes}.reverse
    @pages = Post.all.size/Post::PER_PAGE 
    @pages += 1 if Post.all.size % Post::PER_PAGE > 0
  end

  def show 
  	#binding pry
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user

  	if @post.save
  		flash[:notice] = "Your post was created"
  		redirect_to posts_path
  	else
  		render 'new'
  	end

  end

  def edit; end # ; is used as line separator 

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was updated"
      #redirect_to post_path(@post)
      redirect_to post_path(@post)
    else
      render 'edit', post: @post 
      #render :edit - this also works
    end
  end

  def vote
    #binding pry
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html {
        if @vote.valid?
          flash[:notice] = 'Your vote was counted'
        else
          flash[:error] = "You can vote only once"
        end
        redirect_to :back
      }
      format.js
    end
    
    
  end

  def set_posts
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.user || current_user.admin?)
  end

  private
  def post_params
	   #params.require(:post).permit(:title, :url)  
	   params.require(:post).permit!	
  end

 

end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="well">
	<%= form_for @post do |f| %>
		<div class="control-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="control-group">
			<%= f.label :url %>
			<%= f.text_field :url %>
		</div>
		<div class="control-group">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name  do |cb| %>
			<%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox")+cb.text } %>
		<% end %>
		<br>
		<%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary") %>

	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
	<div class="span0 well text-center">
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
				<i class="icon-arrow-up"></i>
			<% end %>
			<br>
		<% end %>

		<span id="post_<%= post.slug %>_vote" ><%= post.total_votes %> </span>votes
		<br/>
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		<% end %>
	</div>
	<div class="span8 well">
		<%= render post.categories %>
		<h4><%= link_to post.title, fix_url(post.url) %></h4>
		<p><%= post.description %></p>
		<p>
			<span class="quiet">posted by </span> 
				<% if post.user %>
					<%= link_to post.user.username, user_path(post.user) %>
				<% else %>
					username_not_set 
				<% end %>
			<small>at <%= format_date(post.created_at) %></small>
		</p>
		<small>
			<span>
				<%= link_to("#{post.comments.size} comments", post_path(post))%>
			</span>
		</small>
	</div>
	<% if logged_in? %>
		<div class='pull-right'>
			[<%= link_to 'Edit this Post', edit_post_path(post) %>]
		</div>
	<% end %>
</div>

app/views/posts/edit.html.erb
<!--h4>Rails Model backed form helper </h4-->
<%= render 'shared/content_title', title: 'Edit Post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Post' %>

<% @posts.each do |post| %>
	<%= render 'post', post: post %>			
<% end %>		


<% @pages.times do |n| %>
	<% if ((params[:offset].nil? && n == 0) || (params[:offset].to_s == (n * Post::PER_PAGE).to_s)) %>
		<%= "| Page #{n+1}" %>
	<% else %>	
		<%= link_to "| Page #{n+1}", posts_path(offset: n * Post::PER_PAGE) %>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<!--h4>Rails form Helper</h4-->
<% if false %>
	<%= form_tag "/posts" do %>
		<%= label_tag :title , "Input a Title" %>
		<%= text_field_tag :title %>
		<br>
		<%= submit_tag "Create Post", class: "btn btn-primary" %>
	<% end %>
<% end %>

<!--h4>Rails Model backed form helper </h4-->
<%= render 'shared/content_title', title: 'Create New Post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
		<%= render @post.categories %>
		<%= render 'shared/content_title', title: @post.title %>
		<%= link_to @post.title, fix_url(@post.url) %>
		<p><%= @post.description %></p>
		<% if logged_in? %>
			<%= form_for [@post, @comment] do |f| %>
				<%= render 'shared/errors', obj: @comment %>
				<%= f.label :body, 'Leave a comment' %>
				<%= f.text_area :body, rows: 3, class: 'span4'%>
				<br/>
				<%= f.submit 'Create Comment', class: "btn btn-primary" %>
			<% end %>
		<% end %>
</div>

<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
	<%= render 'comments/comment', comment: comment, show_post: false %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.slug %>_vote").html(<%= @post.total_votes %>);
<% else %>
	alert("You are allowed to vote only once");
<% end %>